import { invoke } from "@tauri-apps/api/core";

const API_BASE = "http://127.0.0.1:18765";
const REQUEST_TIMEOUT_MS = 45_000;
const DASHBOARD_COMMAND_DEADLINE_MS = 6_000;

export type BackendRuntimeStatus = { listening: boolean; terminated: boolean; last_error: string | null; recent_output: string[]; port: number; };
export type SystemCapabilities = { pi_web_api: string; local_ai: string; local_ai_runtime?: string; external_ai?: boolean; plant_write_access: boolean; features: string[]; };
export type BridgeUnitTag = { key: string; label: string; unit: string; aliases: string[]; semantic_key?: string; };
export type BridgeUnit = { key: string; name: string; tags: BridgeUnitTag[]; aliases?: string[]; };
export type BridgeSite = { contract_version: string; site: string; read_only: boolean; units: BridgeUnit[]; };
export type SimulatorTag = { key: string; name: string; group: string; unit: string; unit_key?: string; semantic_key?: string; };
export type SimulatorTagsResponse = { mode: string; scope?: string; count: number; items: SimulatorTag[]; };
export type DemoShiftResponse = { mode: string; scope?: string; read_only: boolean; data: Record<string, { Items: Array<{ Timestamp: string; Value: number }> }>; };
export type AssistantReply = { mode: string; read_only: boolean; model: string; answer: string; };
export type RuntimeState = { running: boolean; pid: number | null; binary_path: string; model_path: string; endpoint: string; runtime: string; local_only: boolean; };
export type RuntimeInfo = { readiness: Record<string, unknown>; state: RuntimeState; };
export type SpeechStatus = { ready: boolean; binary: string; model: string; language: string; local_only: boolean; engine: string; cloud: boolean; audio_leaves_device: boolean; };
export type SpeechTiming = { read_ms: number; stt_ms: number; normalize_ms: number; total_ms: number; };
export type SpeechTranscript = { raw_text: string; text: string; confidence: number; confidence_level: "low" | "medium" | "high"; execute_immediately: boolean; corrections: Array<{ source: string; target: string; score: number }>; scope: string; language: string; engine: string; mode?: "partial" | "final"; local_only: boolean; audio_retained: boolean; audio_bytes?: number; timings?: SpeechTiming; };
export type DashboardWidgetLayout = { order: number; width: 3 | 4 | 6 | 8 | 12; height: "compact" | "normal" | "tall"; };
export type DashboardWidget = { id: string; type: "kpi" | "trend" | "average" | "summary"; title: string; unit_key: string; tag_keys: string[]; period: string; layout?: DashboardWidgetLayout; };
export type DashboardWorkspace = { workspace: string; title: string; widgets: DashboardWidget[]; };
export type DashboardCommandResponse = { plan: { action: string; widget?: DashboardWidget; widgets?: DashboardWidget[]; warnings?: string[]; read_only: boolean; }; workspace: DashboardWorkspace; message?: string | null; };
export type KnowledgeManual = { id: string; title: string; revision: string; source_path: string; summary: string; document_date: string | null; status: string; created_at: string; };
export type KnowledgeRevamp = { id: string; title: string; description: string; effective_from: string; effective_to: string | null; approved_by: string; status: string; };
export type KnowledgeOverride = { id: string; subject: string; manual_value: string; current_value: string; reason: string; manual_reference: string; effective_from: string; effective_to: string | null; approved_by: string; status: string; };
export type UnitKnowledge = { unit_key: string; knowledge_status: string; manuals: KnowledgeManual[]; revamps: KnowledgeRevamp[]; overrides: KnowledgeOverride[]; notes: unknown[]; updated_at: string; };
export type ManualSearchItem = { storage_id?: string; chunk_id?: string; page?: number | null; text?: string; score?: number; [key: string]: unknown; };
export type InvestigationExecution = { step: { id: string; tool_name: string; description?: string }; status: string; result?: { data?: unknown; provenance?: Record<string, unknown> } | null; error?: string | null; };
export type InvestigationRun = { plan_id: string; goal: string; completed: boolean; failed: boolean; executions: InvestigationExecution[]; evidence: unknown[]; };
export type InvestigationTimeWindow = { start: string; end: string; interpretation?: string; site_timezone?: string; };
export type InvestigationSynthesis = { evidence_count?: number; ready_for_reasoning: boolean; limitations?: string[]; evidence_package?: Array<Record<string, unknown>>; discovery_evidence?: Array<Record<string, unknown>>; resolved_tags?: string[]; time_window?: InvestigationTimeWindow; };
export type InvestigationDataSource = { mode: "simulated" | "historian"; data_quality: "SIMULATED" | "HISTORIAN"; source: string; process_writes: boolean; };
export type BackendBuildIdentity = { git_sha: string; branch: string; built_at_utc: string | null; embedded: boolean; };
export type EngineeringClaim = { id: string; type: "measured_fact" | "association" | "hypothesis" | "missing_evidence"; statement: string; evidence_ids: string[]; evidence_status: "measured" | "simulated" | "missing"; confidence: "high" | "medium" | "low"; required_evidence: string[]; };
export type HypothesisBranch = { branch_id?:string; priority?:number; score?:number; score_delta?:number; state?:string; status?:string; statement?:string; support_count?:number; contradiction_count?:number; missing_count?:number; causal_status?:string; };
export type InvestigationTrailEntry = { type:string; hypothesis_id?:string; statement?:string; status?:string; supporting_count?:number; contradicting_count?:number; missing_evidence?:string[]; causal_status?:string; round?:number; focus?:string; selected_hypothesis_id?:string; selected_hypothesis_score?:number; hypothesis_ranking?:Array<{id?:string;score?:number;status?:string;missing_count?:number}>; hypothesis_branches?:HypothesisBranch[]; planning_mode?:string; semantic_candidates?:Array<{kind?:string;tag_key?:string;equipment_key?:string;query?:string;reason?:string}>; branch_lifecycle?:HypothesisBranch[]; branch_lifecycle_after_evidence?:HypothesisBranch[]; branch_budget_allocation?:Record<string,number>; branch_budget_mode?:string; branch_budget_explanations?:Array<{hypothesis_branch_id?:string;allocated_calls?:number;state?:string;priority?:number;branch_score?:number;prior_attempts?:number;prior_useful_paths?:number;prior_no_gain_paths?:number;prior_mean_path_gain?:number;reason?:string}>; realized_process_path_gain?:Array<{hypothesis_branch_id?:string;candidate_key?:string;classification?:string;score?:number;relationships?:string[]}>; realized_information_gain?:Array<{tag_key?:string;classification?:string;score?:number;reason?:string}>; actions?:Array<{tool?:string;reason?:string;value?:number;hypothesis_branch_id?:string;branch_score?:number;semantic_candidate?:{kind?:string;tag_key?:string;equipment_key?:string;query?:string;reason?:string}}>; returned_evidence_count?:number; new_evidence_count?:number; new_evidence_ids?:string[]; reconciliation?:{archive_added?:number;events_added?:number;episodes_added?:number}; };
export type EvidenceGraphNode = { id:string; kind:"hypothesis"|"evidence"; label?:string; status?:string; causal_status?:string; source_kind?:string; provenance?:Record<string,unknown>; };
export type EvidenceGraphEdge = { from:string; to:string; relation:string; };
export type InvestigationTrail = { goal?:string; entries?:InvestigationTrailEntry[]; stop_reason?:string; rounds_completed?:number; evidence_count?:number; causal_conclusion?:string; process_control_actions_allowed?:boolean; evidence_graph?:{nodes:EvidenceGraphNode[];edges:EvidenceGraphEdge[]}; semantic_engineering_graph?:{unit_key:string;nodes:Array<{id:string;kind:string;label:string;source_kind?:string;engineering_unit?:string;semantic_key?:string;tag_key?:string}>;edges:Array<{from:string;to:string;relation:string}>;read_only:boolean;causal_inference:boolean}; };
export type EvidenceConfidence = { level:string; score:number; basis:{supporting_independent_evidence:number;contradicting_independent_evidence:number;missing_evidence_items:number}; meaning:string; };
export type EvidenceExplanation = { hypothesis_id?:string; statement?:string; evidence_status?:string; causal_status:string; confidence:EvidenceConfidence; supporting_evidence?:Array<Record<string,unknown>>; contradicting_evidence?:Array<Record<string,unknown>>; missing_evidence?:string[]; };
export type EvidenceConclusion = { observed_facts:Array<{tag_key:string;samples:number;mean?:number;minimum?:number;maximum?:number;delta?:number;evidence_ids:string[]}>; supported_explanations:EvidenceExplanation[]; contradicted_explanations:EvidenceExplanation[]; unresolved_explanations:EvidenceExplanation[]; limitations:string[]; sources:Array<{evidence_id?:string;tool?:string;description?:string;provenance?:Record<string,unknown>}>; overall_causal_conclusion:string; confidence_policy:string; process_control_actions_allowed:boolean; };
export type InvestigationReasoning = { available: boolean; model: string | null; text: string; investigation_trail?:InvestigationTrail; evidence_conclusion?:EvidenceConclusion; hypotheses?:Array<Record<string,unknown>>; claims?: EngineeringClaim[]; validation?: { valid: boolean; violations: Array<{ type: string; text: string }> }; analytics: { summaries: Record<string, Record<string, unknown>>; deviations: Record<string, Record<string, unknown>>; correlations: Array<Record<string, unknown>> } };
export type SavedInvestigation = { id:string; goal:string; unit_key:string|null; status:string; updated_at:string; trail?:InvestigationTrail; resume_context?:Record<string,unknown>; };
export type InvestigationContinuationResponse = { status:string; resolution?:Record<string,unknown>; investigation?:SavedInvestigation; continuation?:{rounds_completed?:number;stop_reason?:string}; reasoning?:InvestigationReasoning; read_only_process_access?:boolean; };
export type InvestigationResponse = { mode: string; backend_build?: BackendBuildIdentity; data_source: InvestigationDataSource; read_only_process_access: boolean; goal: string; unit_key: string; discovery: InvestigationRun; analysis: InvestigationRun | null; synthesis: InvestigationSynthesis; reasoning: InvestigationReasoning; };

async function request<T>(path: string, init?: RequestInit, timeoutMs = REQUEST_TIMEOUT_MS): Promise<T> { const isForm = init?.body instanceof FormData; const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(`${API_BASE}${path}`, { ...init, signal: controller.signal, headers: { ...(isForm ? {} : { "Content-Type": "application/json" }), ...(init?.headers ?? {}) } }); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.detail ?? `${response.status} ${response.statusText}`); } return response.json() as Promise<T>; } catch (error) { if (error instanceof DOMException && error.name === "AbortError") throw new Error(`Local backend request timed out after ${Math.round(timeoutMs / 1000)} seconds.`); throw error; } finally { window.clearTimeout(timeout); } }
const dashboardCommandFlights = new Map<string, Promise<DashboardCommandResponse>>(); let dashboardCommandSequence = 0;
function nextDashboardCommandId(): string { dashboardCommandSequence += 1; return `dashboard-${Date.now()}-${dashboardCommandSequence}`; }
function normalizeDashboardCommand(command: string): string { return command.trim().replace(/[’‘ʼ´`]/g, "'"); }
function dashboardCommand(command: string, workspace = "default"): Promise<DashboardCommandResponse> { const clean = normalizeDashboardCommand(command); const flightKey = `${workspace}\u0000${clean.toLocaleLowerCase()}`; const existing = dashboardCommandFlights.get(flightKey); if (existing) return existing; const commandId = nextDashboardCommandId(); const flight = request<DashboardCommandResponse>("/api/v1/dashboard/command", { method: "POST", body: JSON.stringify({ command: clean, workspace, command_id: commandId }) }, DASHBOARD_COMMAND_DEADLINE_MS).finally(() => { if (dashboardCommandFlights.get(flightKey) === flight) dashboardCommandFlights.delete(flightKey); }); dashboardCommandFlights.set(flightKey, flight); return flight; }
export const api = {
 health:()=>request<{status:string;mode:string}>("/health"),backendRuntimeStatus:()=>invoke<BackendRuntimeStatus>("backend_runtime_status"),capabilities:()=>request<SystemCapabilities>("/api/v1/system/capabilities"),bridgeSite:()=>request<BridgeSite>("/bridge/v1/site"),aiStatus:()=>request<Record<string,unknown>>("/api/v1/ai/status"),aiRuntime:()=>request<RuntimeInfo>("/api/v1/ai/runtime"),startAiRuntime:()=>request<RuntimeState>("/api/v1/ai/runtime/start",{method:"POST"}),stopAiRuntime:()=>request<RuntimeState>("/api/v1/ai/runtime/stop",{method:"POST"}),speechStatus:()=>request<SpeechStatus>("/api/v1/speech/status"),
 transcribeSpeech:(audio:Blob,scope:string,terms:string[],mode:"partial"|"final"="final")=>{const form=new FormData();form.append("audio",audio,"voice-command.wav");form.append("scope",scope);form.append("terms_json",JSON.stringify(terms));form.append("mode",mode);return request<SpeechTranscript>("/api/v1/speech/transcribe",{method:"POST",body:form});},traceVoice:(stage:string,payload:Record<string,unknown>)=>request<{ok:boolean;local_only:boolean}>("/api/v1/speech/trace",{method:"POST",body:JSON.stringify({stage,payload})}),simulatorTags:()=>request<SimulatorTagsResponse>("/api/v1/site-simulator/tags"),demoShift:()=>request<DemoShiftResponse>("/api/v1/site-simulator/demo-shift"),analyze:(question:string,evidence:Record<string,unknown>)=>request<AssistantReply>("/api/v1/ai/analyze",{method:"POST",body:JSON.stringify({question,evidence})}),runInvestigation:(goal:string,unitKey:string)=>request<InvestigationResponse>("/api/v1/investigations/run",{method:"POST",body:JSON.stringify({goal,unit_key:unitKey})},90_000),savedInvestigations:(unitKey:string)=>request<{count:number;items:SavedInvestigation[]}>(`/api/v1/investigations/saved?unit_key=${encodeURIComponent(unitKey)}`),continueInvestigation:(utterance:string,unitKey:string)=>request<InvestigationContinuationResponse>("/api/v1/investigations/continue",{method:"POST",body:JSON.stringify({utterance,unit_key:unitKey})},90_000),
 dashboardWorkspace:(workspace="default")=>request<DashboardWorkspace>(`/api/v1/dashboard/workspaces/${encodeURIComponent(workspace)}`),saveDashboardWorkspace:(workspace:DashboardWorkspace)=>request<DashboardWorkspace>(`/api/v1/dashboard/workspaces/${encodeURIComponent(workspace.workspace)}`,{method:"PUT",body:JSON.stringify({title:workspace.title,widgets:workspace.widgets})}),dashboardCommand,unitKnowledge:(unitKey:string)=>request<UnitKnowledge>(`/api/v1/knowledge/units/${encodeURIComponent(unitKey)}`),effectiveUnitKnowledge:(unitKey:string)=>request<Record<string,unknown>>(`/api/v1/knowledge/units/${encodeURIComponent(unitKey)}/effective`),searchManuals:(unitKey:string,query:string)=>request<{unit_key:string;query:string;count:number;items:ManualSearchItem[]}>(`/api/v1/knowledge/units/${encodeURIComponent(unitKey)}/manuals/search?q=${encodeURIComponent(query)}`),uploadManual:(unitKey:string,file:File,title="",revision="")=>{const form=new FormData();form.append("file",file,file.name);form.append("title",title);form.append("revision",revision);form.append("status","draft");return request<{manual:KnowledgeManual;ingestion:Record<string,unknown>}>(`/api/v1/knowledge/units/${encodeURIComponent(unitKey)}/manuals/upload`,{method:"POST",body:form});},setKnowledgeStatus:(unitKey:string,status:string)=>request<UnitKnowledge>(`/api/v1/knowledge/units/${encodeURIComponent(unitKey)}/status`,{method:"POST",body:JSON.stringify({status})}),engineeringContext:(unitKey:string)=>request<Record<string,unknown>>(`/api/v1/intelligence/context/${encodeURIComponent(unitKey)}`),engineeringAnalyze:(unitKey:string,question:string,processEvidence:Record<string,unknown>)=>request<AssistantReply>("/api/v1/intelligence/analyze",{method:"POST",body:JSON.stringify({unit_key:unitKey,question,process_evidence:processEvidence})}),managementAnalyze:(scopeKind:"complex"|"refinery",scopeId:string,unitKeys:string[],question:string,processEvidenceByUnit:Record<string,Record<string,unknown>>)=>request<AssistantReply>("/api/v1/intelligence/management/analyze",{method:"POST",body:JSON.stringify({scope_kind:scopeKind,scope_id:scopeId,unit_keys:unitKeys,question,process_evidence_by_unit:processEvidenceByUnit})}),
};