import { useState } from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, FlaskConical, Search, ShieldCheck, TrendingUp } from "lucide-react";
import { api, InvestigationResponse, InvestigationRun } from "./api";
import "./InvestigationWorkspace.css";

type TrendPoint={x:string;y:number};type TrendRecord={evidence_id?:string;points?:TrendPoint[]};
function StepList({run,title}:{run:InvestigationRun|null;title:string}){if(!run)return null;return <section className="investigation-block"><h4>{title}</h4><div className="investigation-steps">{run.executions.map(item=><div className="investigation-step" key={item.step.id}><span className={`step-dot ${item.status}`}/><div><strong>{item.step.description||item.step.tool_name}</strong><small>{item.step.tool_name} · {item.status}{item.error?` · ${item.error}`:""}</small></div></div>)}</div></section>}
function TrendChart({tag,record}:{tag:string;record:TrendRecord}){const points=record.points??[];if(points.length<2)return null;const width=720,height=190,pad=24,ys=points.map(p=>p.y),min=Math.min(...ys),max=Math.max(...ys),span=max-min||1;const coords=points.map((p,i)=>({x:pad+(i/(points.length-1))*(width-pad*2),y:height-pad-((p.y-min)/span)*(height-pad*2)}));const path=coords.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ");return <article className="trend-card"><div className="trend-card-head"><div><strong>{tag}</strong><small>{record.evidence_id}</small></div><div className="trend-range"><span>min {min.toFixed(3)}</span><span>max {max.toFixed(3)}</span></div></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${tag} historian trend`} preserveAspectRatio="none"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><line x1={pad} y1={pad} x2={pad} y2={height-pad}/><path d={path}/></svg><div className="trend-time"><span>{points[0].x}</span><span>{points[points.length-1].x}</span></div></article>}
export function InvestigationWorkspace({unitKey,unitName}:{unitKey:string;unitName:string}){
 const[goal,setGoal]=useState("Γιατί ανέβηκε το ΔP του regenerator χθες;"),[result,setResult]=useState<InvestigationResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const canRun=unitKey!=="all"&&goal.trim().length>=3;
 async function run(){if(!canRun)return;setBusy(true);setError(null);setResult(null);try{setResult(await api.runInvestigation(goal.trim(),unitKey));}catch(err){setError(err instanceof Error?err.message:"Investigation failed");}finally{setBusy(false)}}
 const synthesis=result?.synthesis,simulated=result?.data_source?.mode==="simulated",reasoning=result?.reasoning;const analytics=reasoning?.analytics as unknown as Record<string,unknown>|undefined;const trends=(analytics?.trends??{}) as Record<string,TrendRecord>;
 return <section className="investigation-workspace"><div className="investigation-hero"><div><span className="eyebrow">AUTONOMOUS ENGINEERING INVESTIGATION</span><h1>Investigation workspace</h1><p>Goal-driven, source-grounded analysis for {unitName}. The process interface remains read-only.</p></div><span className="readonly-pill"><ShieldCheck size={15}/> Governed · Read-only</span></div>{unitKey==="all"&&<div className="investigation-notice"><AlertTriangle size={18}/> Select a unit before starting a detailed engineering investigation.</div>}
 <div className="investigation-composer"><FlaskConical size={22}/><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe the engineering question or abnormal behavior…"/><button className="primary-button" disabled={!canRun||busy} onClick={()=>void run()}>{busy?"Investigating…":"Run investigation"}</button></div>{error&&<div className="error-banner">{error}</div>}
 {result&&<>{simulated&&<div className="investigation-notice simulated-evidence"><AlertTriangle size={18}/><div><strong>SIMULATED DEVELOPMENT DATA</strong><br/><span>This result is generated from the local deterministic simulator. It is not plant historian evidence and must not be used as an operational conclusion.</span></div></div>}
 <div className="investigation-summary"><article><Search size={18}/><span>Resolved tags</span><strong>{synthesis?.resolved_tags?.length??0}</strong></article><article><CheckCircle2 size={18}/><span>Evidence items</span><strong>{synthesis?.evidence_count??result.discovery.evidence.length}</strong></article><article><ShieldCheck size={18}/><span>Data quality</span><strong>{result.data_source?.data_quality??"UNKNOWN"}</strong></article></div>
 {synthesis?.time_window&&<div className="investigation-window"><strong>Analysis window</strong><span>{synthesis.time_window.start} → {synthesis.time_window.end}</span></div>}<StepList run={result.discovery} title="1 · Discovery"/><StepList run={result.analysis} title={simulated?"2 · Simulated process evidence":"2 · Historian evidence"}/>
 {!!Object.keys(trends).length&&<section className="investigation-block"><div className="reasoning-heading"><TrendingUp size={20}/><div><h4>Process evidence trends</h4><small>Read-only evidence · values shown directly from the investigation data source</small></div></div><div className="trend-grid">{Object.entries(trends).map(([tag,record])=><TrendChart key={tag} tag={tag} record={record}/>)}</div></section>}
 {reasoning&&<section className="investigation-block reasoning-block"><div className="reasoning-heading"><BrainCircuit size={20}/><div><h4>3 · Engineering assessment</h4><small>{reasoning.available?`Local reasoning · ${reasoning.model??"embedded model"}`:"Deterministic evidence only"}</small></div></div><div className="reasoning-text">{reasoning.text}</div><details><summary>Deterministic analytics</summary><pre>{JSON.stringify(reasoning.analytics,null,2)}</pre></details></section>}
 {!!synthesis?.resolved_tags?.length&&<section className="investigation-block"><h4>Resolved process tags</h4><div className="tag-chip-row">{synthesis.resolved_tags.map(tag=><span className="tag-chip" key={tag}>{tag}</span>)}</div></section>}
 <section className="investigation-block"><h4>Evidence & provenance</h4><div className="evidence-grid">{[...(synthesis?.discovery_evidence??[]),...(synthesis?.evidence_package??[])].map((item,index)=><article key={String(item.evidence_id??index)}><strong>{String(item.evidence_id??item.tool??`evidence-${index+1}`)}</strong><pre>{JSON.stringify(item.provenance??{},null,2)}</pre></article>)}</div></section>{!!synthesis?.limitations?.length&&<section className="investigation-block limitation-block"><h4>Limitations</h4>{synthesis.limitations.map((item,index)=><p key={index}><AlertTriangle size={15}/>{item}</p>)}</section>}</>}</section>;
}