import { useEffect, useState } from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, FlaskConical, Search, ShieldCheck, TrendingUp } from "lucide-react";
import { api, EngineeringClaim, InvestigationContinuationResponse, InvestigationResponse, InvestigationRun, InvestigationTimeWindow, SavedInvestigation } from "./api";
import "./InvestigationWorkspace.css";

type TrendPoint={x:string;y:number};type TrendRecord={evidence_id?:string;points?:TrendPoint[]};
function StepList({run,title}:{run:InvestigationRun|null;title:string}){if(!run)return null;return <section className="investigation-block"><h4>{title}</h4><div className="investigation-steps">{run.executions.map(item=><div className="investigation-step" key={item.step.id}><span className={`step-dot ${item.status}`}/><div><strong>{item.step.description||item.step.tool_name}</strong><small>{item.step.tool_name} · {item.status}{item.error?` · ${item.error}`:""}</small></div></div>)}</div></section>}
function TrendChart({tag,record}:{tag:string;record:TrendRecord}){const points=record.points??[];if(points.length<2)return null;const width=720,height=190,pad=24,ys=points.map(p=>p.y),min=Math.min(...ys),max=Math.max(...ys),span=max-min||1;const coords=points.map((p,i)=>({x:pad+(i/(points.length-1))*(width-pad*2),y:height-pad-((p.y-min)/span)*(height-pad*2)}));const path=coords.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ");return <article className="trend-card"><div className="trend-card-head"><div><strong>{tag}</strong><small>{record.evidence_id}</small></div><div className="trend-range"><span>min {min.toFixed(3)}</span><span>max {max.toFixed(3)}</span></div></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${tag} historian trend`} preserveAspectRatio="none"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><line x1={pad} y1={pad} x2={pad} y2={height-pad}/><path d={path}/></svg><div className="trend-time"><span>{points[0].x}</span><span>{points[points.length-1].x}</span></div></article>}
const claimLabels:Record<EngineeringClaim["type"],string>={measured_fact:"Measured fact",association:"Association",hypothesis:"Hypothesis",missing_evidence:"Missing evidence"};
function ClaimPanel({claims}:{claims:EngineeringClaim[]}){if(!claims.length)return null;return <section className="investigation-block claim-block"><div className="reasoning-heading"><ShieldCheck size={20}/><div><h4>Validated engineering claims</h4><small>Machine-checkable statements bound to evidence IDs</small></div></div><div className="claim-grid">{claims.map(claim=><article className={`claim-card ${claim.type}`} key={claim.id}><div className="claim-meta"><span className="claim-type">{claimLabels[claim.type]}</span><span>{claim.confidence} confidence · {claim.evidence_status}</span></div><p>{claim.statement}</p>{!!claim.evidence_ids.length&&<div className="claim-evidence">Evidence: {claim.evidence_ids.map(id=><code key={id}>{id}</code>)}</div>}{!!claim.required_evidence.length&&<div className="claim-required"><strong>Evidence needed:</strong>{claim.required_evidence.map((item,index)=><span key={index}>{item}</span>)}</div>}</article>)}</div></section>}
function EvidenceConclusionPanel({conclusion}:{conclusion?:import("./api").EvidenceConclusion}){
 if(!conclusion)return null;
 const groups=[
  {key:"supported",title:"Supported explanations",items:conclusion.supported_explanations},
  {key:"contradicted",title:"Contradicted explanations",items:conclusion.contradicted_explanations},
  {key:"unresolved",title:"Unresolved explanations",items:conclusion.unresolved_explanations},
 ];
 return <section className="investigation-block conclusion-block"><div className="reasoning-heading"><ShieldCheck size={20}/><div><h4>Evidence-aware conclusion</h4><small>Confidence is evidence sufficiency, not probability of causation</small></div></div>
 {!!conclusion.observed_facts.length&&<div className="conclusion-facts">{conclusion.observed_facts.map(f=><article key={f.tag_key}><span>Observed fact</span><strong>{f.tag_key}</strong><small>{f.samples} samples · mean {String(f.mean??"—")} · Δ {String(f.delta??"—")}</small></article>)}</div>}
 <div className="conclusion-groups">{groups.map(group=><div className={`conclusion-group ${group.key}`} key={group.key}><h5>{group.title} <span>{group.items.length}</span></h5>{group.items.length?group.items.map((item,index)=><article key={item.hypothesis_id??index}><p>{item.statement}</p><div className="confidence-strip"><b>{item.confidence.level}</b><span>Evidence score {item.confidence.score}/100</span><span>support {item.confidence.basis.supporting_independent_evidence}</span><span>contradictions {item.confidence.basis.contradicting_independent_evidence}</span><span>missing {item.confidence.basis.missing_evidence_items}</span></div>{!!item.missing_evidence?.length&&<small>Still needed: {item.missing_evidence.join(" · ")}</small>}</article>):<p className="empty-conclusion">None from current evidence.</p>}</div>)}</div>
 <div className="conclusion-policy"><span>Causal conclusion</span><strong>{conclusion.overall_causal_conclusion}</strong><span>Sources</span><strong>{conclusion.sources.length}</strong><span>Process control</span><strong>{conclusion.process_control_actions_allowed?"Allowed":"Not allowed"}</strong></div></section>;
}
function EvidenceGraphPanel({trail}:{trail?:import("./api").InvestigationTrail}){
 const graph=trail?.evidence_graph;if(!graph?.nodes?.length)return null;
 const hypotheses=graph.nodes.filter(n=>n.kind==="hypothesis");
 const evidence=graph.nodes.filter(n=>n.kind==="evidence");
 return <section className="investigation-block evidence-graph"><div className="reasoning-heading"><Search size={20}/><div><h4>Hypothesis evidence graph</h4><small>Historian, alarms/events, technical archive and previous incidents linked to each hypothesis</small></div></div>
 <div className="evidence-graph-list">{hypotheses.map(h=>{const links=graph.edges.filter(e=>e.to===h.id);return <article className="evidence-graph-branch" key={h.id}><div className="graph-hypothesis"><span>Hypothesis</span><strong>{h.label||h.id}</strong><small>{h.causal_status||"not_established"}</small></div><div className="graph-links">{links.length?links.map((link,index)=>{const source=evidence.find(n=>n.id===link.from);return <div className={`graph-source ${link.relation}`} key={link.from+index}><span className="graph-relation">{link.relation}</span><div><b>{source?.source_kind||"evidence"}</b><strong>{source?.label||link.from}</strong><code>{link.from}</code></div></div>}):<div className="graph-empty">No hypothesis-specific independent evidence linked yet.</div>}</div></article>})}</div>
 <div className="graph-summary"><span>{hypotheses.length} hypotheses</span><span>{evidence.length} evidence sources</span><span>{graph.edges.length} explicit links</span></div></section>;
}
function InvestigationMap({trail}:{trail?:import("./api").InvestigationTrail}){
 const rounds=trail?.entries?.filter(entry=>entry.type==="autonomous_round")??[];
 const latest=rounds[rounds.length-1];
 if(!latest)return null;
 const before=latest.branch_lifecycle??latest.hypothesis_branches??[];
 const after=latest.branch_lifecycle_after_evidence??before;
 if(!after.length)return null;
 const previous=new Map(before.map(branch=>[branch.branch_id,branch]));
 return <section className="investigation-block branch-map"><div className="reasoning-heading"><BrainCircuit size={20}/><div><h4>Live investigation map</h4><small>How evidence changes the priority of competing engineering hypotheses</small></div></div>
 <div className="branch-map-flow"><div className="branch-goal"><span>Investigation goal</span><strong>{trail?.goal??latest.focus??"Engineering investigation"}</strong></div><div className="branch-connector">→</div><div className="branch-lanes">{after.map((branch,index)=>{const prior=previous.get(branch.branch_id);const delta=branch.score_delta??((branch.score??0)-(prior?.score??branch.score??0));const state=branch.state??"keep";return <article className={`branch-lane ${state}`} key={branch.branch_id??index}><div className="branch-head"><span>H{branch.priority??index+1}</span><b>{state}</b></div><p>{branch.statement||branch.branch_id||"Hypothesis"}</p><div className="branch-metrics"><span>priority {branch.priority??"—"}</span><span>score {branch.score?.toFixed(2)??"—"}</span><span>Δ {delta>0?"+":""}{delta.toFixed(2)}</span></div><div className="branch-evidence"><span>support {branch.support_count??0}</span><span>against {branch.contradiction_count??0}</span><span>{branch.causal_status??"not_established"}</span></div></article>})}</div></div>
 {!!latest.realized_information_gain?.length&&<div className="gain-map"><strong>Latest evidence value</strong>{latest.realized_information_gain.map((gain,index)=><span key={gain.tag_key??index}><code>{gain.tag_key??"measurement"}</code> · {gain.classification??"evaluated"} · {gain.score?.toFixed(2)??"—"}</span>)}</div>}</section>;
}
function InvestigationTrailPanel({trail}:{trail?:import("./api").InvestigationTrail}) {
 if(!trail?.entries?.length)return null;
 const hypotheses=trail.entries.filter(e=>e.type==="hypothesis_assessment"),rounds=trail.entries.filter(e=>e.type==="autonomous_round");
 return <section className="investigation-block cockpit-block"><div className="reasoning-heading"><BrainCircuit size={20}/><div><h4>Engineering Investigation Cockpit</h4><small>Auditable hypotheses, autonomous rounds, evidence gaps and stop decision</small></div></div>
 {hypotheses.length>0&&<div className="cockpit-hypotheses">{hypotheses.map((h,index)=><article key={h.hypothesis_id??index}><div className="cockpit-row"><span>Hypothesis</span><b>{h.causal_status==="established"?"Established":"Not established"}</b></div><p>{h.statement}</p><div className="cockpit-counts"><span>Supporting <strong>{h.supporting_count??0}</strong></span><span>Contradicting <strong>{h.contradicting_count??0}</strong></span><span>Status <strong>{h.status??"unresolved"}</strong></span></div>{!!h.missing_evidence?.length&&<div className="cockpit-missing"><AlertTriangle size={14}/><div><strong>Still needed</strong>{h.missing_evidence.map((item,i)=><span key={i}>{item}</span>)}</div></div>}</article>)}</div>}
 {rounds.length>0&&<div className="cockpit-timeline">{rounds.map((r,index)=><article key={r.round??index}><div className="timeline-index">{r.round??index+1}</div><div><div className="cockpit-row"><strong>Autonomous round {r.round??index+1}</strong><span>+{r.new_evidence_count??0} evidence</span></div>{r.focus&&<p className="timeline-focus">Focus: {r.focus}</p>}{r.planning_mode&&<div className="semantic-planning-mode"><BrainCircuit size={13}/><span>{r.planning_mode==="semantic_graph_discovery"?"Semantic graph expanded the investigation":r.planning_mode}</span></div>}{r.branch_budget_allocation&&Object.keys(r.branch_budget_allocation).length>0&&<div className="budget-reallocation"><div className="budget-title"><span>Adaptive hypothesis budget</span><b>{r.branch_budget_mode==="adaptive_information_gain"?"reallocated from evidence gain":"initial balanced allocation"}</b></div><div className="budget-lanes">{Object.entries(r.branch_budget_allocation).map(([branch,calls])=><span key={branch}><code>{branch}</code><strong>{calls} call{calls===1?"":"s"}</strong></span>)}</div>{!!r.realized_process_path_gain?.length&&<div className="budget-gain">{r.realized_process_path_gain.map((gain,index)=><span key={index}><code>{gain.hypothesis_branch_id??"branch"}</code> · {gain.candidate_key??"path"} · <b>{gain.classification??"measured"}</b>{typeof gain.score==="number"?` · gain ${gain.score}`:""}</span>)}</div>}</div>}{!!r.semantic_candidates?.length&&<div className="semantic-candidates">{r.semantic_candidates.map((candidate,i)=><span key={(candidate.tag_key??candidate.equipment_key??candidate.query??"candidate")+i}><b>{candidate.kind??"context"}</b>{" "}{candidate.query??candidate.tag_key??candidate.equipment_key}{candidate.reason&&<small>{" · "}{candidate.reason}</small>}</span>)}</div>}{r.selected_hypothesis_id&&<div className="decision-strip"><span>Selected {r.selected_hypothesis_id}</span><span>Priority {r.selected_hypothesis_score?.toFixed(2)??"—"}</span><span>{r.new_evidence_count??0}/{r.returned_evidence_count??0} genuinely new</span></div>}<div className="timeline-actions">{(r.actions??[]).map((a,i)=><span key={i}><code>{a.tool??"tool"}</code>{a.value!==undefined?` · value ${a.value}`:""}{a.reason?" · "+a.reason:""}</span>)}</div>{r.reconciliation&&<div className="reconciliation-strip"><span>Archive +{r.reconciliation.archive_added??0}</span><span>Events +{r.reconciliation.events_added??0}</span><span>Episodes +{r.reconciliation.episodes_added??0}</span></div>}</div></article>)}</div>}
 <div className="cockpit-stop"><div><span>Stop decision</span><strong>{trail.stop_reason??"Not recorded"}</strong></div><div><span>Rounds</span><strong>{trail.rounds_completed??rounds.length}</strong></div><div><span>Causality</span><strong>{trail.causal_conclusion??"not_established"}</strong></div><div><span>Process control</span><strong>{trail.process_control_actions_allowed?"Allowed":"Not allowed"}</strong></div></div></section>;
}
function formatWindowValue(value:string,timeZone?:string){try{return new Intl.DateTimeFormat("el-GR",{timeZone:timeZone||"UTC",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZoneName:"short"}).format(new Date(value));}catch{return value;}}
function interpretationLabel(window:InvestigationTimeWindow){if(window.interpretation==="previous_local_calendar_day")return "Previous local calendar day";if(window.interpretation==="rolling_24h")return "Rolling 24 hours";if(window.interpretation==="rolling_8h")return "Rolling 8 hours";return window.interpretation||"Resolved period";}
export function InvestigationWorkspace({unitKey,unitName}:{unitKey:string;unitName:string}){
 const[goal,setGoal]=useState("Γιατί ανέβηκε το ΔP του regenerator χθες;"),[result,setResult]=useState<InvestigationResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[saved,setSaved]=useState<SavedInvestigation[]>([]),[continuation,setContinuation]=useState<InvestigationContinuationResponse|null>(null),[resumeBusy,setResumeBusy]=useState(false);
 const canRun=unitKey!=="all"&&goal.trim().length>=3;
 async function loadSaved(){try{const response=await api.savedInvestigations(unitKey);setSaved(response.items);}catch{/* saved investigations are optional until backend is ready */}}
 useEffect(()=>{void loadSaved();},[unitKey]);
 async function resume(item:SavedInvestigation){if(unitKey==="all")return;setResumeBusy(true);setError(null);setContinuation(null);try{const response=await api.continueInvestigation(`continue investigation ${item.goal}`,unitKey);setContinuation(response);await loadSaved();}catch(err){setError(err instanceof Error?err.message:"Unable to continue investigation");}finally{setResumeBusy(false);}}
 async function run(){if(!canRun)return;setBusy(true);setError(null);setResult(null);setContinuation(null);try{setResult(await api.runInvestigation(goal.trim(),unitKey));await loadSaved();}catch(err){setError(err instanceof Error?err.message:"Investigation failed");}finally{setBusy(false)}}
 const synthesis=result?.synthesis,simulated=result?.data_source?.mode==="simulated",reasoning=result?.reasoning;const analytics=reasoning?.analytics as unknown as Record<string,unknown>|undefined;const trends=(analytics?.trends??{}) as Record<string,TrendRecord>;const claims=reasoning?.claims??[];const window=synthesis?.time_window;const build=result?.backend_build;const shortSha=build?.git_sha&&build.git_sha!=="development-unpackaged"?build.git_sha.slice(0,8):build?.git_sha;
 return <section className="investigation-workspace"><div className="investigation-hero"><div><span className="eyebrow">AUTONOMOUS ENGINEERING INVESTIGATION</span><h1>Investigation workspace</h1><p>Goal-driven, source-grounded analysis for {unitName}. The process interface remains read-only.</p></div><span className="readonly-pill"><ShieldCheck size={15}/> Governed · Read-only</span></div>{unitKey==="all"&&<div className="investigation-notice"><AlertTriangle size={18}/> Select a unit before starting a detailed engineering investigation.</div>}
 {unitKey!=="all"&&saved.filter(item=>!item.unit_key||item.unit_key===unitKey).length>0&&<section className="investigation-block saved-investigations"><div className="reasoning-heading"><BrainCircuit size={20}/><div><h4>Saved investigations</h4><small>Resume previous engineering work from its durable checkpoint</small></div></div><div className="saved-investigation-grid">{saved.filter(item=>!item.unit_key||item.unit_key===unitKey).slice(0,6).map(item=><article key={item.id}><div><span>{item.status}</span><strong>{item.goal}</strong><small>{item.updated_at?new Date(item.updated_at).toLocaleString():"Saved locally"}</small></div><button className="primary-button" disabled={resumeBusy} onClick={()=>void resume(item)}>{resumeBusy?"Resuming…":"Continue"}</button></article>)}</div></section>}
 {continuation?.status==="continued"&&<section className="investigation-block continuation-panel"><div className="reasoning-heading"><CheckCircle2 size={20}/><div><h4>Investigation resumed</h4><small>Previous checkpoint → new autonomous evidence round</small></div></div><div className="continuation-flow"><span>Previous investigation</span><b>→</b><span>Resumed</span><b>→</b><span>{continuation.continuation?.rounds_completed??0} new round(s)</span><b>→</b><span>{continuation.continuation?.stop_reason??"assessment complete"}</span></div>{continuation.reasoning?.text&&<div className="reasoning-text">{continuation.reasoning.text}</div>}<InvestigationTrailPanel trail={continuation.reasoning?.investigation_trail}/></section>}
 <div className="investigation-composer"><FlaskConical size={22}/><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe the engineering question or abnormal behavior…"/><button className="primary-button" disabled={!canRun||busy} onClick={()=>void run()}>{busy?"Investigating…":"Run investigation"}</button></div>{error&&<div className="error-banner">{error}</div>}
 {result&&<>{simulated&&<div className="investigation-notice simulated-evidence"><AlertTriangle size={18}/><div><strong>SIMULATED DEVELOPMENT DATA</strong><br/><span>This result is generated from the local deterministic simulator. It is not plant historian evidence and must not be used as an operational conclusion.</span></div></div>}
 <div className="investigation-summary"><article><Search size={18}/><span>Resolved tags</span><strong>{synthesis?.resolved_tags?.length??0}</strong></article><article><CheckCircle2 size={18}/><span>Evidence items</span><strong>{synthesis?.evidence_count??result.discovery.evidence.length}</strong></article><article><ShieldCheck size={18}/><span>Data quality</span><strong>{result.data_source?.data_quality??"UNKNOWN"}</strong></article></div>
 {window&&<div className="investigation-window"><strong>Analysis window</strong><span>{formatWindowValue(window.start,window.site_timezone)} → {formatWindowValue(window.end,window.site_timezone)} · {interpretationLabel(window)} · {window.site_timezone||"UTC"}{shortSha?` · backend ${shortSha}`:""}</span></div>}<StepList run={result.discovery} title="1 · Discovery"/><StepList run={result.analysis} title={simulated?"2 · Simulated process evidence":"2 · Historian evidence"}/>
 {!!Object.keys(trends).length&&<section className="investigation-block"><div className="reasoning-heading"><TrendingUp size={20}/><div><h4>Process evidence trends</h4><small>Read-only evidence · values shown directly from the investigation data source</small></div></div><div className="trend-grid">{Object.entries(trends).map(([tag,record])=><TrendChart key={tag} tag={tag} record={record}/>)}</div></section>}
 <ClaimPanel claims={claims}/><InvestigationMap trail={reasoning?.investigation_trail}/><EvidenceGraphPanel trail={reasoning?.investigation_trail}/><EvidenceConclusionPanel conclusion={reasoning?.evidence_conclusion}/><InvestigationTrailPanel trail={reasoning?.investigation_trail}/>
 {reasoning&&<section className="investigation-block reasoning-block"><div className="reasoning-heading"><BrainCircuit size={20}/><div><h4>3 · Engineering assessment</h4><small>{reasoning.available?`Local reasoning · ${reasoning.model??"embedded model"}`:"Deterministic evidence only"}</small></div></div><div className="reasoning-text">{reasoning.text}</div><details><summary>Deterministic analytics</summary><pre>{JSON.stringify(reasoning.analytics,null,2)}</pre></details></section>}
 {!!synthesis?.resolved_tags?.length&&<section className="investigation-block"><h4>Resolved process tags</h4><div className="tag-chip-row">{synthesis.resolved_tags.map(tag=><span className="tag-chip" key={tag}>{tag}</span>)}</div></section>}
 <section className="investigation-block"><h4>Evidence & provenance</h4><div className="evidence-grid">{[...(synthesis?.discovery_evidence??[]),...(synthesis?.evidence_package??[])].map((item,index)=><article key={String(item.evidence_id??index)}><strong>{String(item.evidence_id??item.tool??`evidence-${index+1}`)}</strong><pre>{JSON.stringify(item.provenance??{},null,2)}</pre></article>)}</div></section>{!!synthesis?.limitations?.length&&<section className="investigation-block limitation-block"><h4>Limitations</h4>{synthesis.limitations.map((item,index)=><p key={index}><AlertTriangle size={15}/>{item}</p>)}</section>}</>}</section>;
}