from __future__ import annotations

from datetime import datetime, timezone
import importlib.util
import platform
import shutil
import subprocess
import sys
from pathlib import Path


def run(command: list[str], cwd: Path) -> None:
    print("+", " ".join(command))
    subprocess.run(command, cwd=cwd, check=True)


def require_modules(modules: dict[str, str]) -> None:
    missing = [package for module, package in modules.items() if importlib.util.find_spec(module) is None]
    if not missing:
        return
    packages = " ".join(missing)
    raise RuntimeError(
        "Missing backend build dependencies: "
        f"{', '.join(missing)}. Install the current backend requirements first with:\n"
        f"  {sys.executable} -m pip install -r backend/requirements.txt\n"
        f"or install the missing package(s):\n  {sys.executable} -m pip install {packages}"
    )


def git_value(root: Path, *args: str, fallback: str) -> str:
    result = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True)
    value = result.stdout.strip() if result.returncode == 0 else ""
    return value or fallback


def write_build_identity(root: Path, backend: Path) -> Path:
    """Create a temporary Python module so PyInstaller embeds the exact source revision."""
    sha = git_value(root, "rev-parse", "HEAD", fallback="unknown")
    branch = git_value(root, "branch", "--show-current", fallback="detached")
    built_at = datetime.now(timezone.utc).isoformat()
    path = backend / "app" / "_build_info.py"
    path.write_text(
        "# Generated by scripts/build-backend-sidecar.py; do not commit.\n"
        f"BUILD_SHA = {sha!r}\n"
        f"BUILD_BRANCH = {branch!r}\n"
        f"BUILD_TIME_UTC = {built_at!r}\n",
        encoding="utf-8",
    )
    print(f"Embedding backend identity: {branch}@{sha} built {built_at}")
    return path


def host_triple() -> str:
    result = subprocess.run(
        ["rustc", "--print", "host-tuple"],
        capture_output=True,
        text=True,
        check=True,
    )
    triple = result.stdout.strip()
    if not triple:
        raise RuntimeError("Could not determine Rust host target triple")
    return triple


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    backend = root / "backend"
    tauri_binaries = root / "desktop" / "src-tauri" / "binaries"
    build_root = root / ".build" / "backend-sidecar"
    dist = build_root / "dist"
    work = build_root / "work"
    spec = build_root / "spec"

    require_modules(
        {
            "PyInstaller": "pyinstaller",
            "fastapi": "fastapi",
            "uvicorn": "uvicorn",
            "multipart": "python-multipart",
        }
    )

    tauri_binaries.mkdir(parents=True, exist_ok=True)
    build_root.mkdir(parents=True, exist_ok=True)
    generated_build_info = write_build_identity(root, backend)

    try:
        run([
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            "--onefile",
            "--name", "fcc-backend",
            "--paths", str(backend),
            "--collect-submodules", "app",
            "--distpath", str(dist),
            "--workpath", str(work),
            "--specpath", str(spec),
            str(backend / "entrypoint.py"),
        ], root)
    finally:
        generated_build_info.unlink(missing_ok=True)

    extension = ".exe" if platform.system() == "Windows" else ""
    source = dist / f"fcc-backend{extension}"
    if not source.exists():
        raise RuntimeError(f"PyInstaller output missing: {source}")

    target = tauri_binaries / f"fcc-backend-{host_triple()}{extension}"
    shutil.copy2(source, target)
    if platform.system() != "Windows":
        target.chmod(target.stat().st_mode | 0o111)

    print(f"Backend sidecar staged: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
